spring:
  datasource:
    # type: org.apache.tomcat.jdbc.pool.Datasource
    url: jdbc:mysql://db:3306/MOMSITTER?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver