server:
  address: 0.0.0.0
  port: 8080

spring:
  redis:
    host: 0.0.0.0
    port: 16379
    password: redis-secret-pw
  datasource:
    # type: org.apache.tomcat.jdbc.pool.Datasource
    url: jdbc:mysql://localhost:3306/MOMSITTER?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    # pool 설정
    hikari:
      connectionTimeout: 20000 # 20 seconds
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    hibernate:
      # ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        "[format_sql]": true

logging:
  level:
    org:
      hibernate: info

secret:
  password: SECRET_KEY
  jwt: SECRET_KEY
