CREATE DATABASE  IF NOT EXISTS `MOMSITTER`;
USE `MOMSITTER`;

--
-- Table structure for table `SITTER_DETAIL`
--

CREATE TABLE `SITTER_DETAIL` (
  `SITTER_NO` bigint NOT NULL AUTO_INCREMENT,
  `INTRODUCE` varchar(1000) DEFAULT NULL,
  `MAX_CARE_AGE` int DEFAULT NULL,
  `MIN_CARE_AGE` int DEFAULT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,  
  PRIMARY KEY (`SITTER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



--
-- Table structure for table `USER`
--

CREATE TABLE `USER` (
  `MEMBER_NO` bigint NOT NULL AUTO_INCREMENT,
  `SITTER_NO` bigint DEFAULT NULL,
  `USER_ID` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `USER_TYPE` varchar(30) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `BIRTHDATE` date NOT NULL,
  `GENDER` varchar(255) NOT NULL,
  `REQUEST_INFO` varchar(1000) DEFAULT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  PRIMARY KEY (`MEMBER_NO`),
  KEY `FK_SITTER_DETAIL_SITTER_NO` (`SITTER_NO`),
  CONSTRAINT `FK_SITTER_DETAIL_SITTER_NO` FOREIGN KEY (`SITTER_NO`) REFERENCES `SITTER_DETAIL` (`SITTER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `CHILD_INFO` (
  `CHILD_NO` bigint NOT NULL AUTO_INCREMENT,
  `MEMBER_NO` bigint DEFAULT NULL,
  `BIRTHDATE` date NOT NULL,
  `GENDER` varchar(30) DEFAULT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  PRIMARY KEY (`CHILD_NO`),
  KEY `FK_USER_INFO_MEMBER_NO` (`MEMBER_NO`),
  CONSTRAINT `FK_USER_INFO_MEMBER_NO` FOREIGN KEY (`MEMBER_NO`) REFERENCES `USER` (`MEMBER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

