openapi: 3.0.0
info:
  title: mom_sitter
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /users/sign-up:
    post:
      tags:
        - General
      summary: 1. 회원가입 - 시터
      description: |-
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | name | (필수)이름 |  |
        | userId | (필수)아이디 |  |
        | password | (필수)비밀번호 | 8~20자리  <br>소문자, 대문자, 특수문자 1개씩 필수 |
        | gender | (필수)성별 | MALE, FEMALE |
        | userType | (필수)유저타입 | PARENT, SITTER |
        | birthDate | (필수) 생년월일 | yyyyMMdd |
        | email | (필수) 이메일 |  |
        | kidsInfo | (부모 필수) 아이 정보 |  |
        | requestInfo | (부모 필수)신청내용 |  |
        | minCareAge | (시터필수) 보육가능 최소 연령 |  |
        | maxCareAge | (시터필수) 보육가능 최대 연령 |  |
        | introduce | (시터필수) 자기 소개 |  |

        ## kidsInfo

        | **key** | **설명** | **범위** |
        | --- | --- | --- |
        | gender | (필수)성별 | MALE, FEMALE |
        | birthDate | (필수) 생년월일 | yyyyMMdd |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 테스터2
                userId: test4
                password: 123123Qq!!
                gender: MALE
                userType: SITTER
                birthDate: '19930101'
                email: test4@gmail.com
                minCareAge: 3
                maxCareAge: 5
                introduce: |-
                  안녕하세요 
                   시터입니다.
      responses:
        '201':
          description: Created
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                memberNo: 3
                createdAt: '2021-12-19T02:23:24.3799835'
                updatedAt: '2021-12-19T02:23:24.3799835'
        '409':
          description: Conflict
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: 이미 가입된 유저입니다
  /users/sign-in:
    post:
      tags:
        - General
      summary: 2. 로그인
      description: |-
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | userId | (필수)아이디 |  |
        | password | (필수)비밀번호 | 8~20자리  <br>소문자, 대문자, 특수문자 1개씩 필수 |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userId: test1
                password: 123123Qq!!
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                accessToken: >-
                  eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2Mzk4NjE1ODksImlhdCI6MTYzOTg0MzU4OSwianRpIjoidGVzdDEifQ.34X10CJ9RmxqbIa15HZvqa-aVgFm6y6m4nOiRWatv38ljZIjgzH9uu_J36hmGxWqaM-X5fzafxAruSeIcRPjow
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 2. 로그인(실패) - 비밀번호
                  value:
                    message: 비밀번호를 확인해주세요
                example-1:
                  summary: 2. 로그인(실패) - 아이디
                  value:
                    message: 아이디를 확인해주세요
  /api/my_info:
    patch:
      tags:
        - General
      summary: 3. 내 정보 업데이트
      description: |-
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | name | (필수)이름 |  |
        | birthDate | (필수) 생년월일 | yyyyMMdd |
        | requestInfo | (부모)신청내용 |  |
        | minCareAge | (시터) 보육가능 최소 연령 |  |
        | maxCareAge | (시터) 보육가능 최대 연령 |  |
        | introduce | (시터) 자기 소개 |  |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 테스터
                birthDate: '19930102'
                minCareAge: 3
                maxCareAge: 5
                requestInfo: 신청내용입니다
                introduce: |-
                  안녕하세요 
                   시터입니다.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                memberNo: 1
                userId: test1
                name: 테스터
                birthdate: '1993-01-01'
                email: test1@gmail.com
                gender: MALE
                userType:
                  - PARENT
                requestInfo: 신청내용입니다
                childInfoList:
                  - childNo: 1
                    gender: MALE
                    birthdate: '2020-01-01'
                    age: 2
                  - childNo: 2
                    gender: FEMALE
                    birthdate: '2018-01-01'
                    age: 4
                sitterDetail: null
        '400':
          description: Bad Request
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 3. 내 정보 업데이트(실패) - 날짜
                  value:
                    message: 날짜는 yyyyMMdd의 형태로 입력해야 합니다
                example-1:
                  summary: 3. 내 정보 업데이트(실패) - 연령 범위
                  value:
                    message: maxCareAge는 minCareAge보다 커야합니다.
    get:
      tags:
        - General
      summary: 6. 내정보 보기
      description: |-
        1.  공통
            

        *   회원번호/이름/생년월일/성별/아이디/이메일
            

        1.  시터회원
            

        *   케어 가능한 최소 연령/자기소개 정보
            

        2\. 부모 회원

        *   아이나이/신청 내용 정보
            

        3\. both : 시터회원 + 부모회원
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                memberNo: 1
                userId: test1
                name: 테스터
                birthdate: '1993-01-01'
                email: test1@gmail.com
                gender: MALE
                userType:
                  - PARENT
                  - SITTER
                requestInfo: 신청내용입니다
                childInfoList:
                  - childNo: 1
                    gender: MALE
                    birthdate: '2020-01-01'
                    age: 2
                  - childNo: 2
                    gender: FEMALE
                    birthdate: '2018-01-01'
                    age: 4
                  - childNo: 5
                    gender: MALE
                    birthdate: '2019-01-04'
                    age: 3
                sitterDetail:
                  minCareAge: 3
                  maxCareAge: 5
                  introduce: |-
                    안녕하세요 
                     시터입니다.
  /api/my_info/password:
    patch:
      tags:
        - General
      summary: 3-1. 비밀번호 변경
      description: |-
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | password | (필수)비밀번호 | 8~20자리  <br>소문자, 대문자, 특수문자 1개씩 필수 |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                password: 123123Qq!!
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: text/plain;charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '7'
          content:
            text/plain:
              schema:
                type: string
              example: success
  /api/my_info/child:
    put:
      tags:
        - General
      summary: 3-2. 아이 신규 등록
      description: '*   아이 추가'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                gender: FEMALE
                birthDate: '20180103'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                - childNo: 1
                  gender: MALE
                  birthdate: '2020-01-01'
                  age: 2
                - childNo: 2
                  gender: FEMALE
                  birthdate: '2018-01-01'
                  age: 4
                - childNo: 5
                  gender: FEMALE
                  birthdate: '2018-01-03'
                  age: 4
        '400':
          description: Bad Request
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 3-2. 아이 신규 등록(실패) - 날짜
                  value:
                    message: 날짜는 yyyyMMdd의 형태로 입력해야 합니다
                example-1:
                  summary: 3-2. 아이 신규 등록(실패) - 성별
                  value:
                    message: 올바른 gender를 입력해주세요
    patch:
      tags:
        - General
      summary: 3-3. 아이 수정
      description: |-
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | childNo | (필수)아이 번호 |  |
        | gender | (필수)성별 | MALE, FEMALE |
        | birthDate | (필수) 생년월일 | yyyyMMdd |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                childNo: 5
                gender: MALE
                birthDate: '20190104'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                - childNo: 1
                  gender: MALE
                  birthdate: '2020-01-01'
                  age: 2
                - childNo: 2
                  gender: FEMALE
                  birthdate: '2018-01-01'
                  age: 4
                - childNo: 5
                  gender: MALE
                  birthdate: '2019-01-04'
                  age: 3
        '400':
          description: Bad Request
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 3-3. 아이 수정(실패) -성별
                  value:
                    message: 올바른 gender를 입력해주세요
                example-1:
                  summary: 3-3. 아이 수정(실패) -날짜
                  value:
                    message: 날짜는 yyyyMMdd의 형태로 입력해야 합니다
        '401':
          description: Unauthorized
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: 올바르지 않은 아이입니다.
  /api/my_info/user_type/parent:
    patch:
      tags:
        - General
      summary: 4. 부모로도 활동하기
      description: |-
        추가적인 정보를 제출 받아서 시터 혹은 부모로도 서비스를 이용할 수 있도록, 지원

        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | kidsInfo | (필수) 아이 정보 |  |
        | requestInfo | (필수)신청내용 |  |

        ## kidsInfo

        | **key** | **설명** | **범위** |
        | --- | --- | --- |
        | gender | (필수)성별 | MALE, FEMALE |
        | birthDate | (필수) 생년월일 | yyyyMMdd |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                kidsInfo:
                  - gender: MALE
                    birthDate: '20200101'
                  - gender: FEMALE
                    birthDate: '20180101'
                requestInfo: 신청내용입니다
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                memberNo: 1
                userId: test1
                name: 테스터
                birthdate: '1993-01-01'
                email: test1@gmail.com
                gender: MALE
                userType:
                  - PARENT
                  - SITTER
                requestInfo: 신청내용입니다
                childInfoList:
                  - childNo: 1
                    gender: MALE
                    birthdate: '2020-01-01'
                    age: 2
                  - childNo: 2
                    gender: FEMALE
                    birthdate: '2018-01-01'
                    age: 4
                  - childNo: 5
                    gender: MALE
                    birthdate: '2019-01-04'
                    age: 3
                sitterDetail:
                  minCareAge: 3
                  maxCareAge: 5
                  introduce: |-
                    안녕하세요 
                     시터입니다.
        '403':
          description: Forbidden
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: 이미 부모로 활동중입니다.
  /api/my_info/user_type/sitter:
    patch:
      tags:
        - General
      summary: 5. 시터로도 활동하기
      description: |-
        *   시터 타입 추가시 입력 required
            
        # body 설명

        | **key** | **설명** | **비고** |
        | --- | --- | --- |
        | minCareAge | (필수) 보육가능 최소 연령 |  |
        | maxCareAge | (필수) 보육가능 최대 연령 |  |
        | introduce |  자기 소개 |  |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                minCareAge: 3
                maxCareAge: 5
                introduce: |-
                  안녕하세요 
                   시터입니다.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Token {{token}}
      responses:
        '200':
          description: OK
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                memberNo: 1
                userId: test1
                name: 테스터
                birthdate: '1993-01-01'
                email: test1@gmail.com
                gender: MALE
                userType:
                  - PARENT
                  - SITTER
                requestInfo: 신청내용입니다
                childInfoList:
                  - childNo: 1
                    gender: MALE
                    birthdate: '2020-01-01'
                    age: 2
                  - childNo: 2
                    gender: FEMALE
                    birthdate: '2018-01-01'
                    age: 4
                  - childNo: 5
                    gender: MALE
                    birthdate: '2019-01-04'
                    age: 3
                sitterDetail:
                  minCareAge: 3
                  maxCareAge: 5
                  introduce: |-
                    안녕하세요 
                     시터입니다.
        '403':
          description: Forbidden
          headers:
            
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: 이미 시터로 활동중입니다.